EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Models/AddVisitViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EaseHealthDemoProject.Areas.Doctor.Models
{
    public class AddVisitViewModel
    {
        [Key]
        public int VisitId { get; set; }

        public int UserId { get; set; }

        public string VisitName { get; set; }

        public DateTime VisitDate { get; set; }
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Models/AvailabilityViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EaseHealthDemoProject.Areas.Doctor.Models
{
    public class AvailabilityViewModel
    {
        public int UserId { get; set; }
        [Key]
        public bool Day { get; set; }

        public string SelectedDay { get; set; }

        public int StartTimeId { get; set; }
       
        public TimeSpan StartTime { get; set; }

        public SelectList StartTimeList { get; set; }

        public int EndTimeId { get; set; }

        public TimeSpan EndTime { get; set; }

        [NotMapped]
        public SelectList EndTimeList { get; set; }

        public TimeSpan BreakStartTime { get; set; }

        public TimeSpan BreakCloseTime { get; set; }

        public string[] SelectedDayDetails { get; set; }

        public int AvailabilityId { get; set; }

    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Models/DisplayDoctorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EaseHealthDemoProject.Areas.Doctor.Models
{
    public class DisplayDoctorViewModel
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        [Display(Name = "Mobile Number")]
        public string MobileNumber { get; set; }

         [Display(Name = "State Name")]
        public string StateName { get; set; }

        [Display(Name = "City Name")]
        public string CityName { get; set; }

        [Display(Name = "Locality Name")]
        public string LocalityName { get; set; }

        [Display(Name = "Pincode")]
        public string Pincode { get; set; }

        public string User { get; set; }

        [Display(Name = "Qualification Name")]
        public string QualificationName { get; set; }

        [Display(Name = "Speciality Name")]
        public string SpecialityName { get; set; }

        [Display(Name = "License Number")]
        public string LicenseNumber { get; set; }

        [Display(Name = "Clinic Registration Number")]
        public string ClinicRegistrationNumber { get; set; }

        [Display(Name = "Experience")]
        public string Experience { get; set; }
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Models/DoctorAvailabilityDayDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EaseHealthDemoProject.Areas.Doctor.Models
{
    public class DoctorAvailabilityDayDetails
    {
       public class AvailabilityDetails
        {
            public string SelectedDay { get; set; }
            public string StartTime { get; set; }
            public string EndTime { get; set; }
            public List<Break> BreakList { get; set; }
        }
        public class Break
        {
            public string BreakStartTime { get; set; }
            public string BreakCloseTime { get; set; }
        }
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Models/DoctorEditProfileViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EaseHealthDemoProject.Areas.Doctor.Models
{
    public class DoctorEditProfileViewModel
    {
        public int UserId { get; set; }
        public string FullName { get; set; }

        [Phone]
        [Key]
        [Display(Name = "MobileNumber")]
        public string MobileNumber { get; set; }


        public int StateId { get; set; }
        public string StateName { get; set; }
        [NotMapped]
        public SelectList StateList { get; set; }


        public int CityId { get; set; }
        public string CityName { get; set; }
        [NotMapped]
        public SelectList CityList { get; set; }


        public int LocalityId { get; set; }
        public string LocalityName { get; set; }
        [NotMapped]
        public SelectList LocalityList { get; set; }

        public string Pincode { get; set; }

        
        public int QualificationId { get; set; }
        public string QualificationName { get; set; }
        public SelectList QualificationList { get; set; }


        public int SpecialityId { get; set; }
        public string SpecialityName { get; set; }
        [NotMapped]
        public SelectList SpecialityList { get; set; }

        public string LicenseNumber { get; set; }

        public string ClinicRegistrationNumber { get; set; }

        public string Experience { get; set; }
        

        public string SelectedQualificationList { get; set; }
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Models/DoctorFeedbackViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EaseHealthDemoProject.Areas.Doctor.Models
{
    public class DoctorFeedbackViewModel
    {
        
        public int FeedbackId { get; set; }

        public int UserId { get; set; }

        public string Sender { get; set; }

        public string Feedback { get; set; }
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Models/DoctorInvoiceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EaseHealthDemoProject.Areas.Doctor.Models
{
    public class DoctorInvoiceViewModel
    {
        
        

        public int UserId { get; set; }

        public int VisitId { get; set; }

        
        [Display(Name = "InvoiceId")]
        [Required]
        public int InvoiceId { get; set; }      

        [Required]
        [Display(Name = "Total Amount")]
        public float TotalAmount { get; set; }
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Models/DoctorVisitViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EaseHealthDemoProject.Areas.Doctor.Models
{
    public class DoctorVisitViewModel
    {
        public int VisitId { get; set; }

        [Display(Name = "Visit Name")]
        
        public string VisitName { get; set; }

        public int PatientId { get; set; }

        [Display(Name = "Patient Name")]
        
        public string PatientName { get; set; }
        
        [NotMapped]
        public SelectList PatientList { get; set; }

        public int UserId { get; set; }

        [Display(Name="Visit Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")] 
        [DataType(DataType.Date)]       
        public string VisitDate { get; set; }

        [Display(Name= "Visit Details")]       
        public string VisitDetails { get; set; }

        public float TotalAmount { get; set; }
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Controllers/DoctorController.cs
using EaseHealthDemoProject.Areas.Doctor.Models;
using EaseHealthDemoProject.Areas.Main.Controllers;
using EaseHealthDemoProject.Areas.Main.Models;
using EaseHealthDemoProject.BusinessLayer;
using EaseHealthDemoProject.DataAccessLayer;
using Microsoft.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EaseHealthDemoProject.Areas.Doctor.Controllers
{
    public class DoctorController : Controller
    {
        [AuthorizeUserAccessLevel(UserRole.Doctor)]
        public ActionResult DoctorProfile()
        {
            try
            {
                int userId; 
                int.TryParse((Session["userId"]).ToString(), out userId);
                DoctorBL doctor = new DoctorBL();
                return View(doctor.DisplayDoctor(userId));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
        }

        [AuthorizeUserAccessLevel(UserRole.Doctor)]
        public ActionResult Feedback()
        {
            try
            {
                int userId;
                int.TryParse((Session["userId"]).ToString(), out userId);
                FeedbackBL doctor = new FeedbackBL();
                return View(doctor.DisplayFeedback(userId));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
        }

        [AuthorizeUserAccessLevel(UserRole.Doctor)]
        public ActionResult Availability()
        {
            try
            {
               AvailabilityBL availability = new AvailabilityBL();
                return View(availability.GetTimeList());
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
        }
         
        [HttpPost]       
        public ActionResult Availability(string[] availabilityDetails)
        {
            try 
            {
                if (ModelState.IsValid)
                {
                    int userId;
                    int.TryParse((Session["userId"]).ToString(), out userId);
                    AvailabilityBL availability = new AvailabilityBL();
                    AvailabilityViewModel availabilityViewModel = new AvailabilityViewModel();
                    availabilityViewModel.SelectedDayDetails = availabilityDetails;
                    availabilityViewModel.UserId = userId;
                    availability.AddAvailability(availabilityViewModel);
                    return RedirectToAction("Availability");
                }
                else
                    return View();
            }
            catch(Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
           
        }
        
        [AuthorizeUserAccessLevel(UserRole.Doctor, UserRole.Patient)]
        public ActionResult DisplayAvailability(int? id)
        {
            try
            {
                if (id != null)
                {
                    AvailabilityBL doctor = new AvailabilityBL();
                    return View(doctor.DisplayDoctorAvailability(id));
                }
                else
                {
                    return RedirectToAction("Unauthorized", "Home", new { area = "Main" });
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }


        }

        [AuthorizeUserAccessLevel(UserRole.Doctor, UserRole.Patient)]
        public ActionResult DisplayBreakAvailability(int id)
        {
            try
            {
                AvailabilityBL doctor = new AvailabilityBL();
                return View(doctor.DisplayDoctorBreakAvailability(id));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }

        }

        [AuthorizeUserAccessLevel(UserRole.Doctor)]
        public ActionResult DoctorVisit()
        {
            try
            {
                int userId;
                int.TryParse((Session["userId"]).ToString(), out userId);
                VisitBL visit = new VisitBL();
                var visitList = visit.DoctorDisplayVisit(userId);
                return View(visitList);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
        }

        [AuthorizeUserAccessLevel(UserRole.Doctor)]
        public ActionResult VisitDetails(int id)
        {
            try
            {
                Session["visitId"] = id;
                VisitBL visit = new VisitBL();
                DoctorVisitViewModel visitDetails = new DoctorVisitViewModel();
                visitDetails.VisitDetails = visit.DoctorDisplayVisitDetails(id);
                return View(visitDetails);
            }
            catch
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VisitDetails(DoctorVisitViewModel doctorVisitViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int visitId;
                    int.TryParse((Session["VisitId"]).ToString(), out visitId);
                    VisitBL visit = new VisitBL();
                    doctorVisitViewModel.VisitId = visitId;
                    visit.AddDoctorVisitDetails(doctorVisitViewModel);
                   ViewBag.Message = "Your data has been saved successfully";
                   doctorVisitViewModel.VisitDetails = visit.DoctorDisplayVisitDetails(visitId);
                   return View(doctorVisitViewModel);
                }
                else
                    return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
        }

        [AuthorizeUserAccessLevel(UserRole.Doctor)]
        public ActionResult AddVisit()
        {
            try
            {
                DoctorVisitViewModel doctorVisitViewModel = new DoctorVisitViewModel();
                VisitBL addVisit = new VisitBL();
                doctorVisitViewModel = addVisit.GetPatientList();
                return View(doctorVisitViewModel);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddVisit(DoctorVisitViewModel doctorVisitViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                   
                    int userId;
                    VisitBL visit = new VisitBL();
                    int.TryParse((Session["userId"]).ToString(), out userId);
                    doctorVisitViewModel.UserId = userId;                    
                    visit.AddDoctorVisit(doctorVisitViewModel);
                    ViewBag.Message = "Your data has been saved successfully";
                    VisitBL addVisit = new VisitBL();
                    doctorVisitViewModel=addVisit.GetPatientList();
                    return View(doctorVisitViewModel);
                }
                else
                    return RedirectToAction("Error", "Home", new { area = "Main" });
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }

        }

        [AuthorizeUserAccessLevel(UserRole.Doctor)]
        public ActionResult AddInvoice(int id)
        {
            try
            {
                DoctorInvoiceViewModel doctorInvoiceViewModel = new DoctorInvoiceViewModel();
                Session["visitId"] = id;
                VisitBL invoice = new VisitBL();
                doctorInvoiceViewModel = invoice.DoctorDisplayInvoice(id);
                return View(doctorInvoiceViewModel);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddInvoice(DoctorInvoiceViewModel doctorInvoiceViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int visitId;
                    int.TryParse((Session["visitId"]).ToString(), out visitId);
                    VisitBL invoice = new VisitBL();
                    doctorInvoiceViewModel.VisitId = visitId;
                    invoice.AddInvoice(doctorInvoiceViewModel);
                    ViewBag.Message = "Your data has been saved successfully";
                    doctorInvoiceViewModel = invoice.DoctorDisplayInvoice(visitId);
                    return View(doctorInvoiceViewModel);
                   
                }
                else
                    return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
        }

        [AuthorizeUserAccessLevel(UserRole.Doctor)]
        public ActionResult EditProfile()
        {
            try
            {
                int userId;
                int.TryParse((Session["userId"]).ToString(), out userId);
                DoctorEditProfileViewModel editProfileViewModel = new DoctorEditProfileViewModel();
                editProfileViewModel.UserId = userId;
                DoctorBL doctor = new DoctorBL();

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Views/Doctor/AddInvoice.cshtml
@model EaseHealthDemoProject.Areas.Doctor.Models.DoctorInvoiceViewModel
@{

}
@Html.Partial("_DoctorProfileNavbar")
<meta name="viewport" content="width=device-width" />
<div id="loginScreen_invoice">
    @using (Html.BeginForm("AddInvoice", "Doctor", FormMethod.Post, new { @class = "form-horizontal form-horizontal_invoice", role = "form" }))
    {
        @Html.AntiForgeryToken()
       
        @Html.Label("Invoice", new { @class = "pageheading" })
        if (@ViewBag.message != null)
        {
            <div class="error-notice">
                <div class="oaerror info ">
                    <span> @ViewBag.message</span>
                </div>
            </div>
        }
        <div class="invoice">
            @Html.Label("Total Amount*", new { @class = "col-md-4 control-label left-label_invoice" })
            @Html.TextBoxFor(model => model.TotalAmount, new { @class = " col-md-4 form-control right_textbox_invoice", id = "reciever_textbox" })
            @Html.ValidationMessage("", new { @class = "text-danger" })
            <span class="fa fa-inr rupee"> </span>
        </div>
        //-------------------------------------------------------------------------------------------------------Submit  Button
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default submit_invoice" value="Save Visit" id="loginbutton_soap" />
            </div>
        </div>
    }
</div>
<div id="cover_soap ">

</div>

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Views/Doctor/AddVisit.cshtml
@model EaseHealthDemoProject.Areas.Doctor.Models.DoctorVisitViewModel
@{
    ViewBag.Title = "AddVisit";
}


@Html.Partial("_DoctorProfileNavbar")

<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<!-- Bootstrap Date-Picker Plugin -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
<meta name="viewport" content="width=device-width" />
<div id="loginScreen_addvisit">
    <div id="box-cover_addvisit">
        @using (Html.BeginForm("AddVisit", "Doctor", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary("", new { @class = "text-danger" })
            @Html.Label("Add Visit Here!", new { @class = "pageheading" })
            if (@ViewBag.message != null)
            {
                <div class="error-notice">
                    <div class="oaerror info ">
                        <span> @ViewBag.message</span>
                    </div>
                </div>
            }
            <div class="form-group label_addvisitname">
                @Html.Label("VisitName*", new { @class = "col-md-4 control-label label_addvisit" })
                <div class="col-md-12">
                    @Html.TextBoxFor(m => m.VisitName, new { @class = "form-control input addvisitname right_textbox_addvisit", id = "visitname_textbox" })
                    @Html.ValidationMessage("", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group label_addvisitname">
                @Html.Label("PatientName*", new { @class = "col-md-4 control-label label_addvisit" })
            </div>
            <div class="address-div">
                <div class="align-patientdropdown">
                    @Html.DropDownListFor(model => model.PatientName, Model.PatientList, "Patient", new { @class = "btn btn-default addvisitpatient dropdown-toggle right_textbox_addvisit", id = "patient" })
                </div>
                @Html.ValidationMessage("", new { @class = "text-danger" })
            </div>
            <div id="patientname_validation">

            </div>
            <div class="form-group label_addvisitname">
                @Html.Label("Visit Date*", new { @class = "col-md-4 control-label label_addvisit" })
                <div class="col-md-2 mii_addvisit">
                    <div class='input-group date ' data-provide="datepicker">
                        <span class="input-group-addon input-group-addon_addvisit calendar"> </span>
                        @Html.TextBoxFor(model => model.VisitDate, new { @class = "col-md-12 date_textbox addvisitdate right_textbox_addvisit", id = "datetimepicker1_addvisit", Value = "" })
                        @Html.ValidationMessage("", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div id="dov_validation">

            </div>
            //-------------------------------------------------------------------------------------------------------Submit  Button
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default loginbutton_addvisit" value="Save Visit" id="loginbutton_addvisit" />
                </div>
            </div>
            //-------------------------------------------------------------------------------------------------------

        }
    </div>
</div>
<div id="cover ">
</div>

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Views/Doctor/DisplayAvailability.cshtml
@model IEnumerable<EaseHealthDemoProject.Areas.Doctor.Models.AvailabilityViewModel>

@{

}

@Html.Partial("_DoctorProfileNavbar")
@Html.Label("Availability", new { @class = "availability_pageheading" })
@if(Model.Count() > 0)
{
<div id="gridContent">
    @{
        var grid = new WebGrid(Model, canPage: true, rowsPerPage: 7, defaultSort: "SelectedDay",
        selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
        grid.Pager(WebGridPagerModes.NextPrevious);
    }
    @grid.GetHtml(tableStyle: "webGrid",
                    headerStyle: "header",
                    alternatingRowStyle: "alt",
                    selectedRowStyle: "select",
                    columns: grid.Columns(
                              grid.Column("SelectedDay", "Day"),
                              grid.Column("StartTime", "Start Time"),
                              grid.Column("EndTime", "End Time"),
                              grid.Column("Break Details", format: (item) =>
                                    {
                                        var links = Html.ActionLink("Get Breaks", "DisplayBreakAvailability", "Doctor", new { id = item.AvailabilityId }, null);
                                        return Html.Raw(links.ToString());
                                    })
                           ))
</div>
    }
  else
    {
<div class="oaerror info">
    <span> No data found.</span>
</div>
    }

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Views/Doctor/DoctorProfile.cshtml
@model IEnumerable<EaseHealthDemoProject.Areas.Doctor.Models.DisplayDoctorViewModel>


@{
    ViewBag.Title = "DoctorProfile";
}


@Html.Partial("_DoctorProfileNavbar")
@Html.Label("Your Profile", new { @class = "availability_pageheading" })

    
        @foreach (var item in Model)
        {
            
    <div class="container">
        <div class="row">   
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">@Html.DisplayFor(modelItem => item.FullName)</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="~/Content\Images\doctor.png" class=" img-responsive"> </div>

                                <div class=" col-md-9 col-lg-9 ">
                                    <ul class="table table-user-information">
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model => model.MobileNumber):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.MobileNumber)</li>
                                        </ul>
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model => model.StateName):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.StateName)</li>
                                        </ul>
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model => model.CityName):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.CityName)</li>
                                        </ul>
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model => model.LocalityName):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.LocalityName)</li>
                                        </ul>
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model => model.Pincode):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.Pincode)</li>
                                        </ul>
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model=> model.QualificationName):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.QualificationName)</li>
                                        </ul>
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model=> model.SpecialityName):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.SpecialityName)</li>
                                        </ul>
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model => model.LicenseNumber):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.LicenseNumber)</li>
                                        </ul>
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model => model.ClinicRegistrationNumber):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.ClinicRegistrationNumber)</li>
                                        </ul>
                                        <ul>
                                            <li class="record">@Html.DisplayNameFor(model => model.Experience):</li>
                                            <li class="data">@Html.DisplayFor(modelItem => item.Experience) yrs</li>
                                        </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            @Html.ActionLink("Profile", "EditProfile", "Doctor", new { @class = " btn btn-sm btn-success glyphicon glyphicon-edit" })


                        </div>

                    </div>
                </div>
            </div>
    </div>
        }

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Doctor/Views/Doctor/DoctorVisit.cshtml
@model IEnumerable<EaseHealthDemoProject.Areas.Doctor.Models.DoctorVisitViewModel>

@Html.Partial("_DoctorProfileNavbar")

@Html.Label("All Visits", new { @class = "availability_pageheading" })

<script src="../../Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>


<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        @Html.ActionLink("Add Visit", "AddVisit", "Doctor", new { @class = " btn-success text-success addvisit_button" })
    </div>
</div>

@if(Model.Count() > 0)
    {
    <div id="gridContent">
        @{
            var grid = new WebGrid(Model, canPage: true, rowsPerPage: 10,
            selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContent");
            grid.Pager(WebGridPagerModes.NextPrevious);
        }
        @grid.GetHtml(tableStyle: "webGrid",
            headerStyle: "header",
            alternatingRowStyle: "alt",
     
     previousText: "< Prev",
     nextText: "Next >",
     
            selectedRowStyle: "select",
            columns: grid.Columns(

                        grid.Column("VisitName", "Visit Name", style: "description"),
                        grid.Column("VisitDate", " Visit Date"),
                        grid.Column("PatientName", "Patient Name"),
                        grid.Column("Visit Details", format: (item) =>
                        {
                            var links = Html.ActionLink("Add Details", "VisitDetails", "Doctor", new { id = item.VisitId },null);
                            return Html.Raw(links.ToString());
                        }),
                        grid.Column("Invoice", format: (item) =>
                        {
                            var links = Html.ActionLink("Add Invoice", "AddInvoice", "Doctor", new { id = item.VisitId }, null);
                            return Html.Raw(links.ToString());
                        })


     ))

    </div>
    }
    else
    {
    <div class="form-group">
        <div class="col-md-12 ">
            <div class="oaerror info">
                <span> No data found.</span>
            </div>
            </div>
</div>
            }