EaseHealthDemoProject/EaseHealthDemoProject/Areas/Patient/Models/DisplayPatientViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EaseHealthDemoProject.Areas.Patient.Models
{
    public class DisplayPatientViewModel
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        [Display(Name = "Mobile Number")]
        public string MobileNumber { get; set; }

        [Display(Name = "State Name")]
        public string StateName { get; set; }

        [Display(Name = "City Name")]
        public string CityName { get; set; }

        [Display(Name = "Locality Name")]
        public string LocalityName { get; set; }

        [Display(Name = "Pincode")]
        public string Pincode { get; set; }

        [Display(Name = "Bloodgroup Name")]
        public string BloodGroupName { get; set; }

        public string Gender { get; set; }


        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")] 
        [Display(Name = "Date Of Birth")]
        public string DateOfBirth { get; set; }

        [Display(Name = "Secondary Phone Number")]
        public string SecondaryPhoneNumber { get; set; }

       
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Patient/Models/FeedbackViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace EaseHealthDemoProject.Areas.Patient.Models
{
    public class FeedbackViewModel
    {
        
        public int UserId { get; set; }
        
        public int DoctorId { get; set; }

        [Required]
        [Display(Name = "Doctor Name")]
        public string DoctorName { get; set; }
        
        [NotMapped]
        public SelectList DoctorList { get; set; }

        [Required]
        public string FeedbackContent { get; set; }
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Patient/Models/PatientVisitViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EaseHealthDemoProject.Areas.Patient.Models
{
    public class PatientVisitViewModel
    {
        public int VisitId { get; set; }

        [Display(Name = "Visit Name")]
        public string VisitName { get; set; }

        [Display(Name = "Doctor Name")]
        public string DoctorName { get; set; }

        public int DoctorId { get; set; }

        public int PatientId { get; set; }

        public int UserId { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")] 
        [Display(Name = "Visit Date")]
        public string VisitDate { get; set; }

        [Display(Name = "Visit Details")]
        public string VisitDetails { get; set; }

        public float TotalAmount { get; set; }
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Patient/Controllers/PatientController.cs
using EaseHealthDemoProject.Areas.Patient.Models;

using EaseHealthDemoProject.BusinessLayer;
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EaseHealthDemoProject.DataAccessLayer;
using EaseHealthDemoProject.Areas.Main.Controllers;
using System.Web.UI;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;


namespace EaseHealthDemoProject.Areas.Patient.Controllers
{
    public class PatientController : Controller
    {
        [AuthorizeUserAccessLevel(UserRole.Patient)]
        public ActionResult PatientProfile()
        { 
            try
            {
            int userId;           
            int.TryParse((Session["userId"]).ToString(), out userId);
            PatientBL patient = new PatientBL();
            return View(patient.DisplayPatient(userId));
            }
            catch(Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });                
            }

        }

        [AuthorizeUserAccessLevel(UserRole.Patient)]
        public ActionResult Feedback()
        {
            try
            {
                FeedbackBL feedback = new FeedbackBL();
                return View(feedback.LoadDoctorList());
            }            
            catch(Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });                
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Feedback(FeedbackViewModel feedbackViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int userId;
                    int.TryParse((Session["userId"]).ToString(), out userId);
                    FeedbackBL feedback = new FeedbackBL();
                    feedbackViewModel.UserId = userId;
                    feedback.FeedbackRegister(feedbackViewModel);                    
                    ViewBag.Message = "Your data has been saved successfully";                    
                    return View(feedback.LoadDoctorList());
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }
            
        }

        [AuthorizeUserAccessLevel(UserRole.Patient)]
        public ActionResult Visit()
        {
            try
            {
                int userId;
                int.TryParse((Session["userId"]).ToString(), out userId);
                VisitBL patient = new VisitBL();
                return View(patient.PatientDisplayVisit(userId));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }            
        }


        [AuthorizeUserAccessLevel(UserRole.Patient)]
        public ActionResult GeneratePdf()
        {
            try
            {
                int userId;
                int.TryParse((Session["userId"]).ToString(), out userId);
                VisitBL patient = new VisitBL();
                return View(patient.PatientDisplayVisit(userId));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { area = "Main" });
            }      
        } 
    }
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Patient/Views/Patient/Feedback.cshtml
@model EaseHealthDemoProject.Areas.Patient.Models.FeedbackViewModel
@{
    ViewBag.Title = "Feedback";
}
@Html.Partial("_PatientPartial")
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<meta name="viewport" content="width=device-width" />
<div id="loginScreen_feedback">
    <div id="box-cover_Feedback">
        @using (Html.BeginForm("Feedback", "Patient", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.Label("Add Feedback Here!", new { @class = "availability_pageheading" })
            if (@ViewBag.message != null)
            {
                <div class="error-notice">
                    <div class="oaerror info ">
                        <span> @ViewBag.message</span>
                    </div>
                </div>
            }
            <div class="form-group">
                @Html.Label("DoctorName*", new { @class = "col-md-4 control-label label_addvisit" })
            </div>
            <div class="address-div">
                <div class="align-patientdropdown">
                    @Html.DropDownListFor(model => model.DoctorName, Model.DoctorList, "Doctor", new { @class = "btn btn-default doctor dropdown-toggle doctor right_textbox_addvisit", id = "doctor" })
                    @Html.ValidationMessage("", new { @class = "text-danger" })
                </div>
            </div>
            <div id="doctor_validation">

            </div>
            <div class="form-group">
                @Html.Label("Feedback*", new { @class = "col-md-4 control-label label_addvisit" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.FeedbackContent, new { @class = "form-control feedbackcontent right_textbox_feedback", id = "reciever_textbox" })
                    @Html.ValidationMessage("", new { @class = "text-danger" })
                </div>
            </div>

            //-------------------------------------------------------------------------------------------------------Submit  Button
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default feedback_submitbutton" value="Save Feedback" id="feedback_submitbutton" />
                </div>
            </div>
            //-------------------------------------------------------------------------------------------------------

        }
    </div>
</div>
<div id="cover_feedback">
</div>

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Patient/Views/Patient/GeneratePdf.cshtml
@model IEnumerable<EaseHealthDemoProject.Areas.Patient.Models.PatientVisitViewModel>
@using iTextSharp.text;
    @using iTextSharp.text.pdf;
@{
        Layout = null;
        
        Response.AddHeader("Content-disposition", "attachment; filename=report.pdf");
        Response.ContentType = "application/octet-stream";
        var doc = new Document();
        
        PdfWriter writer = PdfWriter.GetInstance(doc, Response.OutputStream);
        doc.SetPageSize(PageSize.A4.Rotate());
        var arial = FontFactory.GetFont("Arial", 12, Color.BLACK);
        var arialBold = FontFactory.GetFont("Arial", 14, Font.BOLD, Color.BLACK);
        doc.Open();
        try
        {
            PdfContentByte cb = writer.DirectContent;
            string imageURL = Server.MapPath(".") + "/image2.jpg";
            cb.BeginText();
            try
            {                
                cb.SetFontAndSize(BaseFont.CreateFont(), 14);
                cb.SetTextMatrix(200,350);
                var table = new PdfPTable(5)
                {
                    TotalWidth = 700f,
                    SpacingAfter = 12f,
                    LockedWidth = true,                    
                   SpacingBefore = 400f
                };
                PdfPCell cell = new PdfPCell(new Phrase("Your Visit Details are here! \n You can take a print out of this. Get Well Soon !!",
                        new Font(Font.HELVETICA, 18F)));
                cell.Colspan = 5;
                cell.HorizontalAlignment = 1; //0=Left, 1=Centre, 2=Right
                //Style
                
                cell.Border = Rectangle.BOTTOM_BORDER; // | Rectangle.TOP_BORDER;
                cell.BorderWidthBottom = 3f;
                cell.PaddingBottom = 10f;
                table.AddCell(cell);
                
                table.HorizontalAlignment = 1;              
                
              
                    table.AddCell(new Phrase("Visit Name", arialBold));
                    table.AddCell(new Phrase("Visit Date", arialBold));
                    table.AddCell(new Phrase("Doctor Name", arialBold));
                    table.AddCell(new Phrase("Visit Details", arialBold));
                    table.AddCell(new Phrase("Total Amount", arialBold));
               
                foreach (var item in Model)
                {
                    table.AddCell(new Phrase(item.VisitName.ToString(), arial));
                    table.AddCell(new Phrase(item.VisitDate.ToString(), arial));
                    table.AddCell(new Phrase(item.DoctorName, arial));
                    table.AddCell(new Phrase(item.VisitDetails.ToString(), arial));
                    table.AddCell(new Phrase("₹ " + item.TotalAmount.ToString(), arial));
                  
                }
             
                doc.Add(table);
                
            }
            finally
            {
                cb.EndText();
            }

        }
        finally
        {
            doc.Close();
            writer.Close();
           
        }
           

    }

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Patient/Views/Patient/PatientProfile.cshtml
@model IEnumerable<EaseHealthDemoProject.Areas.Patient.Models.DisplayPatientViewModel>
@{
    ViewBag.Title = "PatientProfile";
}

@Html.Partial("_PatientPartial")
@Html.Label("Your Profile", new { @class = "availability_pageheading" })

@foreach (var item in Model)
{

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">@Html.DisplayFor(modelItem => item.FullName)</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">                            
                            <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="~/Content\Images\patient.png" class=" img-responsive"> </div>

                            <div class=" col-md-9 col-lg-9 ">
                                <ul class="table table-user-information">
                                    <ul>
                                        <li class="record">@Html.DisplayNameFor(model => model.MobileNumber):</li>
                                        <li class="data">@Html.DisplayFor(modelItem => item.MobileNumber)</li>
                                    </ul>
                                    <ul>
                                        <li class="record">@Html.DisplayNameFor(model => model.StateName):</li>
                                        <li class="data">@Html.DisplayFor(modelItem => item.StateName)</li>
                                    </ul>
                                    <ul>
                                        <li class="record">@Html.DisplayNameFor(model => model.CityName):</li>
                                        <li class="data">@Html.DisplayFor(modelItem => item.CityName)</li>
                                    </ul>
                                    <ul>
                                        <li class="record">@Html.DisplayNameFor(model => model.LocalityName):</li>
                                        <li class="data">@Html.DisplayFor(modelItem => item.LocalityName)</li>
                                    </ul>
                                    <ul>
                                        <li class="record">@Html.DisplayNameFor(model => model.Pincode):</li>
                                        <li class="data">@Html.DisplayFor(modelItem => item.Pincode)</li>
                                    </ul>
                                    <ul>
                                        <li class="record">@Html.DisplayNameFor(model => model.BloodGroupName):</li>
                                        <li class="data">@Html.DisplayFor(modelItem => item.BloodGroupName)</li>
                                    </ul>
                                    <ul>
                                        <li class="record">@Html.DisplayNameFor(model => model.Gender):</li>
                                        <li class="data">@Html.DisplayFor(modelItem => item.Gender)</li>
                                    </ul>
                                    <ul>
                                        <li class="record">@Html.DisplayNameFor(model => model.DateOfBirth):</li>
                                        <li class="data">@Html.DisplayFor(modelItem => item.DateOfBirth)</li>
                                    </ul>
                                    <ul>
                                        <li class="record">@Html.DisplayNameFor(model => model.SecondaryPhoneNumber):</li>
                                        <li class="data">@Html.DisplayFor(modelItem => item.SecondaryPhoneNumber)</li>
                                    </ul>                                   
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        


                    </div>

                </div>
            </div>
        </div>
    </div>
}

EaseHealthDemoProject/EaseHealthDemoProject/Areas/Patient/Views/Patient/Visit.cshtml
@model IEnumerable<EaseHealthDemoProject.Areas.Patient.Models.PatientVisitViewModel>

@{

}

@Html.Partial("_PatientPartial")
@Html.Label("Your Visit Details", new { @class = "availability_pageheading" })
@if(Model.Count() > 0)
{
<div id="gridContent">
    @{
        var grid = new WebGrid(Model, canPage: true, rowsPerPage: 5,
        selectionFieldName: "selectedRow", ajaxUpdateContainerId: "gridContentInvoice");
        grid.Pager(WebGridPagerModes.NextPrevious);
     }
    @grid.GetHtml(tableStyle: "webGrid",
            headerStyle: "header",
            htmlAttributes: new { id = "DataTable" },
            alternatingRowStyle: "alt",
            selectedRowStyle: "select", mode: WebGridPagerModes.All,
            firstText: "<< First",
            previousText: "< Prev",
            nextText: "Next >",
            lastText: "Last >>",
            columns: grid.Columns(
                      grid.Column("VisitId", "VisitId"),
                      grid.Column("VisitName", "Visit Name", style: "description"),
                      grid.Column("VisitDate", " Visit Date"),
                      grid.Column("DoctorName", "Doctor Name"),
                      grid.Column("VisitDetails", "Visit Details"),
                      grid.Column("TotalAmount", "Invoice(₹)")
                      ))
</div>
            <a href="#" class="btn  btn-sm   btn-default btn-success text-success " id="button_exportToPdf">
                Export To Pdf
            </a>
}
 else
    {
<div class="oaerror info">
    <span> No data found.</span>
</div>
    }